### ISSUE TITLE
Codemirror syntax highlighting on blog posts

### ISSUE THREAD

**Issue by jakealbaugh** [CodePen/redesign#1]
Codemirror doesn't appear to be running on code blocks in posts, language is specified. 

Three language example in [this post](http://redesign.codepen.io/ImagineProgramming/post/a-lovely-post-for-jake) courtesy of @imagine-programming.

Seems like theres a first line tab issue as well. I am guessing thats an artifact of the markdown processor and corrected by Codemirror auto indent or whatever.

**Post on Redesign**
[post on redesign](http://redesign.codepen.io/ImagineProgramming/post/class-inheritance-in-javascript)

![Redesign](https://cloud.githubusercontent.com/assets/352330/10112198/cfe4ba2a-639e-11e5-9f10-823260e51c07.png)

**Original Post**
[post on current](http://codepen.io/ImagineProgramming/blog/class-inheritance-in-javascript)
![Original](https://cloud.githubusercontent.com/assets/352330/10112220/f82075c4-639e-11e5-8f79-68f12d293346.png)

**Comment by chriscoyier** [comment]
fixed
