### ISSUE TITLE
Get rid of the avatar frame or disable transparent PNGs

### ISSUE THREAD

**Issue by fallenartist** [CodePen/redesign#100]
The frame around avatar doesn't add anything here, does it?

![screen shot 2015-10-01 at 15 56 47](https://cloud.githubusercontent.com/assets/661820/10224363/6c6c262a-6855-11e5-86a4-1f70e69f2ac8.png)

**Comment by chriscoyier** [comment]
I'll fill the background white so it doesn't look weird. If you want to remove the border, you can apply custom CSS to your profile at https://codepen.io/you/settings/customize
