### ISSUE TITLE
Margin between footer buttons in Pen are inconsistent

### ISSUE THREAD

**Issue by edadams** [CodePen/redesign#102]
The margins between buttons in the footer on a Pen, [for example here](http://codepen.io/lbebber/pen/ojBzmy), are inconsistent. The Collections, Embed, etc. buttons have different margins to the Share and Export buttons.

![image](https://i.gyazo.com/c7861a93951b06584cf3efb4cf04cb31.png)

(Difficult to see here, so you may wanna click it!)

This also gets me wondering if we need to have two buttons at separate sides of the screen - it doesn't really make sense to me that Embed is on the left side, but Export is on the right side when they perform similar functions. I feel like the Export button should perhaps contain the Embed button's functionality, or at the very least the Embed button should be grouped with the Export and Share buttons given their functional similarities.

**Comment by chriscoyier** [comment]
Good eye! We'll get that fixed up. And yeah I think moving the embed over to the other side DOES make sense.
