### ISSUE TITLE
Settings View - New template bug...maybe

### ISSUE THREAD

**Issue by gandhiShepard** [CodePen/redesign#103]
When clicking on the "down arrow" next to the New Pen button on the Settings page, the "New Pen from Template" text does not appear. It just looks like a long thin line.

<img width="1585" alt="screen shot 2015-10-01 at 10 06 43 am" src="https://cloud.githubusercontent.com/assets/8546059/10224570/42d60d66-6824-11e5-9d5b-ad7fd5062f81.png">

Great work on the redesign! I'm lovin it! High fives!

**Comment by chriscoyier** [comment]
Tracking this one here: https://github.com/CodePen/redesign/issues/84

Any leads would be appreciated!
