### ISSUE TITLE
"View Compiled" link when panel is collapsed

### ISSUE THREAD

**Issue by zslabs** [CodePen/redesign#105]
If the CSS panel (for example) is collapsed, the close button is disabled since clicking it would do nothing. I also think that any other auxiliary links, like `View Compiled` should also be disabled, since clicking them doesn't do a whole bunch for you.

**Comment by chriscoyier** [comment]
If it's collapsed you can't even see the View Compiled button though, right?

**Comment by chriscoyier** [comment]
Ohhhhhhhh, but not in Left or Right editor modes. That's a good point.

**Comment by desandro** [comment]
Got it. Fix has been committed.
