### ISSUE TITLE
Profile URLs case sensitive

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#107]
codepen.io/MarieMosley 404s
codepen.io/mariemosley works

**Comment by chriscoyier** [comment]
Yep, this is totally a bug. It's a long-standing bug though. We have it open in our private bug tracker for now, as it's not really related to the redesign. I think we have somewhat of a plan for fixing.

**Comment by daviddarnes** [comment]
@mariemosley thanks for reporting!

@chriscoyier top notch! Oh of course, I just dropped onto the site and thought I'd test it out incase a fix was pushed during or before the redesign launch.
