### ISSUE TITLE
Unable to Re-Expand Editor

### ISSUE THREAD

**Issue by Murilirum** [CodePen/redesign#110]
I can close (well minimize now) the various editors, but I cannot seem to figure out how (or if) I can re-enable  the editors when I need to use them.

![](https://i.imgur.com/Bf7OksR.png)

**Comment by chriscoyier** [comment]
If you hover over them, it gives you the tip that you can double-click to expand them. 

Also, it makes your mouse pointer into an Up-Down arrow thingy. Meaning: just grab it and drag it back up.

**Comment by Murilirum** [comment]
> Up-Down arrow thingy

I needed that chuckle today. Thanks @chriscoyier!

However, there is no tip that appears for me when I hovered, it just displayed the title "Close". The click and drag solution did work.

```
Google Chrome Version 45.0.2454.101 m, Windows 7 (x64)
```

In case that's of any relevance. I'll check it on my mac when I get to that part of my day.

**Comment by Murilirum** [comment]
Double clicking did not work either (no errors in the Chrome DevTools).
