### ISSUE TITLE
#view-switcher still clickable after hiding

### ISSUE THREAD

**Issue by desandro** [CodePen/redesign#111]
**Steps to reproduces**

1. In open, click **Change View**
2. Click outside View Switcher dialog to hide it

**Expected result**: View Switcher is completely hidden and in-actionable

**Actual result**: links & buttons in View Switcher are still clickable. View Switcher opacity is 0, but it's still there.

Assigning to myself for now.

**Comment by chriscoyier** [comment]
Fixed
