### ISSUE TITLE
manual run in editor does not work

### ISSUE THREAD

**Issue by pixelass** [CodePen/redesign#115]
When I try to use the manual run nothing happens (compiled tab stays empty)

![cdpnbug](https://cloud.githubusercontent.com/assets/1148334/10227591/87c77654-686e-11e5-9126-d4e748fb80eb.gif)

I tried different preprocessors too. It seems the button just doesn't work at all

**Comment by carlschooff** [comment]
Just want to verify that I am experiencing the same issue.
Pixelass, nice work on the gif!

**Comment by pixelass** [comment]
also: no error in the console

**Comment by chriscoyier** [comment]
Was a duplicate ID problem. Derp. Fix going up.
