### ISSUE TITLE
Can't click 'recent pens' links after viewing notifications

### ISSUE THREAD

**Issue by rachsmithcodes** [CodePen/redesign#121]
To reproduce:
1. Go to user homepage
2. Click notifications icon (bell)
3. Close notifications by clicking anywhere else on the page
4. Try to click a link in recent pens

This doesn't seem to happen when you close notifications by clicking on the icon again, only when you click somewhere else on the page to make them go away.
Only happens when window is sized so that notifications panel "covers" recent pens links
![screenshot 2015-10-01 10 28 01](https://cloud.githubusercontent.com/assets/1632086/10228392/38311768-6827-11e5-95e4-19869e3ab2b6.png)

**Comment by quezo** [comment]
@rachsmithcodes Does this happen consistently for you? I'm unable to recreate it.

**Comment by rachsmithcodes** [comment]
I can make it happen every time I click to open notifications then close by clicking off the panel, here's a video
https://drive.google.com/drive/u/0/my-drive

**Comment by rachsmithcodes** [comment]
This is on Chrome 45.0.2454.101 OSX El Capitan

**Comment by pixelass** [comment]
this is where the click targets

<img width="520" alt="screen shot 2015-10-01 at 8 06 48 pm" src="https://cloud.githubusercontent.com/assets/1148334/10229339/08232920-6878-11e5-9403-7d992daef23c.png">

Seems the container is still covering the section

**Comment by chriscoyier** [comment]
This was a weird one. I fixed it. 

The way that our regular dropdowns close is different than the way our generic "click away" function closes things. Fortunately callbacks on the later can call the former and it works.
