### ISSUE TITLE
Showcase thumbnails overlaying radio buttons below search box

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#122]
http://codepen.io/user/organize/

Thumbnails in "Drag from here" area are covering the radio buttons for the search:

![screenshot 2015-10-01 14 35 40](https://cloud.githubusercontent.com/assets/456844/10230176/d0851e8e-6849-11e5-9cf5-d17f72b7fdea.png)

**Comment by JanKantyPawelski** [comment]
![screen shot 2015-10-02 at 00 31 24](https://cloud.githubusercontent.com/assets/6461935/10235577/e13ef476-689d-11e5-9293-0628dbdcb3d4.png)

Have also some additional position bug in setting our profile thumbnails.

**Comment by chriscoyier** [comment]
I fixed the search form one... but the screwed up grid on the right hand side I can't seem to replicate. Gonna close for now, but if you can replicate every time @JanKantyPawelski hit me with browser specifics.
