### ISSUE TITLE
Title without spaces on the collection

### ISSUE THREAD

**Issue by jorgeatgu** [CodePen/redesign#125]
The title in one line without spaces overpass the width of the box

<img width="419" alt="captura de pantalla 2015-10-01 a las 20 57 41" src="https://cloud.githubusercontent.com/assets/2649175/10230779/43ebc852-687f-11e5-80be-c3351f041e2b.png">

*Great job with the redesign!*

**Comment by chriscoyier** [comment]
I think hiding overflow is the only real solution here.... tough call since it doesn't really hurt much if the text sticks out, but it is a bit weird. I guess hiding overflow might potentially contain other weird display issues, should they arise, so I'll give it a shot!
