### ISSUE TITLE
Comment Modal no 'Escape' functionality

### ISSUE THREAD

**Issue by rkhayat** [CodePen/redesign#126]
This is a UX issue. The comment modal for a pen has no 'escape' functionality to close it, which forces us to scroll back up in order to close it.

Two fixes include - 
-attach ```#drawer-close-button``` to a header, and have it fixed (allowing us to close it even after scrolled)
-escape to close.

Thanks.

**Comment by chriscoyier** [comment]
Escape key coming in next deploy!
