### ISSUE TITLE
clicking .stats heart does nothing

### ISSUE THREAD

**Issue by rkhayat** [CodePen/redesign#129]
clicking ```.stats``` heart does nothing, the comments seems to go to the pen, but that functionality could be moved to ```.stats``` since clicking the heart does nothing.

**Comment by chriscoyier** [comment]
Can you be more specific? If it's your own Pen, clicking that heart should do nothing. If it's someone else's it should heart the Pen and increment the number. If that doesn't work on a particular page, re-open and let us know.

**Comment by rkhayat** [comment]
Hey @chriscoyier this occurs when you are viewing your own profile, your own pens.
