### ISSUE TITLE
settings panel "save" button hidden/cropped

### ISSUE THREAD

**Issue by andyhullinger** [CodePen/redesign#130]
Presenter mode on laptop forces save button off screen (inaccessible)

p.s. My students kept losing the button in other situations too, we're all on laptops so screen real estate is constrained.

<img width="1467" alt="screen shot 2015-10-01 at 2 05 56 pm" src="https://cloud.githubusercontent.com/assets/1874134/10231162/e6cb8514-6846-11e5-9b85-d3a13a9afc0b.png">

**Comment by Fotiman** [comment]
Dup of issue #92

**Comment by chriscoyier** [comment]
I'm gonna leave it open, cause I think we can nudge it farther up the page in Presentation Mode and give it more breathing room.
