### ISSUE TITLE
Missing Feature - pens by tags missing

### ISSUE THREAD

**Issue by rkhayat** [CodePen/redesign#131]
Before Redesign I used to be able to click a tag and see all pens associated with it, this is not visible after redesign, is there any plan to bring it back?

**Comment by chriscoyier** [comment]
Tags aren't as emphasizes, but yes, if you click a Pen's tag (for example, from the Details View of a Pen), you go there. 

http://codepen.io/tag/flexbox/

**Comment by rkhayat** [comment]
What about codepen.io/tags ? it redirects. It used to be the following ...http://i.imgur.com/AHNAJ6C.png

**Comment by desandro** [comment]
+1 I found tags easier to use over collections

**Comment by rkhayat** [comment]
@desandro  Indeed, when I am looking for inspiration, I look at tags.
