### ISSUE TITLE
Example preview in Editor settings doesn't update

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#132]
https://codepen.io/user/settings/editor

Changes to the Syntax Highlighting, fonts, etc., don't appear in the Example preview.
![screenshot 2015-10-01 15 30 15](https://cloud.githubusercontent.com/assets/456844/10231538/5aa5dda4-6851-11e5-8be6-8d97eefc9cc9.png)

**Comment by chriscoyier** [comment]
Fix going out in next deploy!
