### ISSUE TITLE
Better Access to Profile "click on gravatar?! broken"

### ISSUE THREAD

**Issue by andyhullinger** [CodePen/redesign#133]
Like the re-design (kinda hate the homepage toll-booth) would highly prefer on login to come to my profile directly, or restore the old behavior of clicking on my picture"gravatar" as a direct link to my profile page.

**Comment by chriscoyier** [comment]
Thanks for the feedback! I'm afraid we don't consider either of these things a bug at the moment, but we'll always be considering things like this as we move forward.
