### ISSUE TITLE
Next Page button didn't display the content on search page

### ISSUE THREAD

**Issue by shaohaolin** [CodePen/redesign#134]
Enjoy the new UI; however, when I try to search some cool pens. The next page button is not display correctly, missing next page content. I have taken a screen shot.
![codepen-nextpagebug](https://cloud.githubusercontent.com/assets/6677092/10231707/461be198-6852-11e5-9dfc-cb264c4fd227.png)

**Comment by chriscoyier** [comment]
Tracking this one here: https://github.com/CodePen/redesign/issues/78
