### ISSUE TITLE
Text In Embed a pen session doesn't align and only have one button per page

### ISSUE THREAD

**Issue by shaohaolin** [CodePen/redesign#136]
In the Embed a pen session:

You can select post, collection, and other option. However, the text is block by pens.
Also, not sure the next and prev buttons are having problem or not, because I only have one button per page.
![codepen-embedpenbuy](https://cloud.githubusercontent.com/assets/6677092/10232073/7517f4b2-6854-11e5-9a1b-e8a50ebd559d.png)

**Comment by chriscoyier** [comment]
Fixing! (shouldn't have those radio buttons at all here).
