### ISSUE TITLE
Browser history seriously busted

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#137]
There are too many writes to browser history happening when viewing some pages. I wasn't able to track down exactly what's going on but some pages require 3-4 'back' operations to actually get back to where you were.

The easiest to see is probably the collections page, since you can actually watch the URL change from '/collections' to '/collections/picks,' which requires 2 clicks to get away from.

**Comment by alexzaworski** [comment]
Apparently you can sometimes get straight up stuck on a page where it'll take 5-10 'backs' to make it out, fairly frustrating for users who are accustomed to using the keyboard for forward/back nav.

**Comment by chriscoyier** [comment]
Hey Alex!

We actually don't do much manual manipulation of the browser history. Pages like that are just different content that you navigate to by pressing regular old links. 

I'm not able to understand exactly where you got confused, but if you wanna shoot a quick screencast or something and explain, we're listening.

**Comment by alexzaworski** [comment]
Hi Chris,

Thanks for the speedy reply. I'm not sure what I'm running into, then, but here are steps to reproduce on my end:

1. Go to CodePen home
2. Navigate to collections via main nav
3. Click the browser back button (page doesn't update at all)
4. Click the browser back button (correctly navigates back to home page)

I used collections as an example because the URL actually changes from "/collection" to "/collections/picks" in a bout a half second which makes me think it's some sort of redirect issue, but I have the same problem on the pens and posts pages as well.

If this is still confusing I'd be happy to shoot you a screencast if you point me in the direction of some software.

**Comment by chriscoyier** [comment]
Ah yes! There is a weird redirect happening there for sure. Reopening for a fix.

**Comment by chriscoyier** [comment]
@quezo Those steps outlined above do the thing. /collections/ insta-redirects to /collections/picks/ - we should probably just leave it be /collections/ and have it show picked.

**Comment by peter-mouland** [comment]
I also get browser history issue:
 * from the homepage, click a `picked pen`
 * go back
 * go forward

**Expected result:** to be on your picked pen
**Actual Result:** You are still on the homepage

**Comment by chriscoyier** [comment]
Related weird bug, if you're ON http://codepen.io/collections/picks/ and refresh, the bottoms ones don't show up.

**Comment by alexzaworski** [comment]
Sort of implied but that also happens if you get a direct link to that page (I don't see anything in the explore section when I click your link).

**Comment by jakealbaugh** [comment]
Related: 

1. paginate a few pages into any collection
2. hit 'back'—pens update *correctly*.
3. paginate forwards again
4. select a pen
5. hit 'back' to return to collection page `x`—pens load correctly
6. continue hitting back—url is updated correctly, but pens don't update.

**Comment by jakealbaugh** [comment]
adding to https://github.com/CodePen/redesign/issues/137#issuecomment-146963150:

From that page you need to hit back three times to return to a previous page as well.

**Comment by quezo** [comment]
Okay. This bug just got fixed. Thanks for documenting this error. If you find anything else please let me know.
