### ISSUE TITLE
Text in Picked Pens does not match the image and content

### ISSUE THREAD

**Issue by shaohaolin** [CodePen/redesign#138]
In Picked Pens session, somehow there are duplicates images in different pens.
That causes the link of the pen is not correct or matched to the image.

See the screen shot:

![codepen-imagenotmatchtext](https://cloud.githubusercontent.com/assets/6677092/10233323/ce2c028a-685b-11e5-824f-94d4886cb7df.png)

**Comment by chriscoyier** [comment]
yeah this is SUPER weird. Tracking here: https://github.com/CodePen/redesign/issues/90
