### ISSUE TITLE
Responsive Tables for List Views

### ISSUE THREAD

**Issue by tomhodgins** [CodePen/redesign#139]
Hi! I'm loving the redesign, one thing that I can see an easy improvement for is the tables!

Right now they have a minimum width, and if the table happens to be narrower than the container holding it you can scroll left and right. This is okay, but not the most intuitive, and certainly not the best way to present the information.

I had to create responsive tables for a fantasy sports web app and I came up with an all-CSS solution that looked great, but as soon as we started putting the tables into different layouts we began having all kind of issues with the breakpoints :/

So to remedy this, so we can finally have responsive tables that work everywhere I helped created an @element query polyfill so the breakpoints can be relative to how wide the table renders on the page.

Here's a pen using these @element queries to have a responsive layout: http://codepen.io/tomhodgins/pen/xwGdGd

…and here is the CSS-based demo page for the original responsive tables I did that convinced me that we needed element queries: http://staticresource.com/tables/

I was going to write @element query-based responsive table styles and load them in my own browser as a user script — if I were to write responsive table styles that worked on the tables across the site, is there any chance of it being implemented?

**Comment by chriscoyier** [comment]
That's some pretty cool fancy dancin' - but as our data is slightly more predictable I'm just gonna fiddle with some media queries and shuffling things around.

![Uploading Screen Shot 2015-10-07 at 12.18.57 PM.png…]()
