### ISSUE TITLE
Author link on anonymous Pens 404s

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#142]
"Secret Sam" link 404s from Editor view
![screenshot 2015-10-01 17 33 46](https://cloud.githubusercontent.com/assets/456844/10234441/99870a64-6862-11e5-8468-3a90279601ad.png)

**Comment by chriscoyier** [comment]
We should just not link this at all.

**Comment by quezo** [comment]
Good catch. Will go up with next push.

**Comment by shivamchopra** [comment]
You can thank me here as well ;)
