### ISSUE TITLE
Button to close redesign modal overflows on small screens

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#144]
![screenshot_20151001203300](https://cloud.githubusercontent.com/assets/456844/10234694/4fa39d34-6864-11e5-8375-8af8b7743001.png)

**Comment by chriscoyier** [comment]
I'll probably change the wording on that button =)  I just was worried people would hate that modal on day one. But since people didn't seem to mind, we should probably tweak it and use it for news more often like we used to.
