### ISSUE TITLE
Media Queries not Working in Editor View

### ISSUE THREAD

**Issue by SirDaev** [CodePen/redesign#147]
I have a single media query that engages in every view except 'Editor View'. I have tested it in multiple modern browser versions, all with the same result. My pen in particular can be see here:

http://codepen.io/SirDaev/pen/dYprKz

This pen has not been edited since before the update, and was working correctly beforehand.

**Comment by chriscoyier** [comment]
Bug! Tracking here: https://github.com/CodePen/redesign/issues/146
