### ISSUE TITLE
You Can't Scroll the Editor in the "Top" Layout

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#15]
See the no-scrollbar:

<img width="458" alt="2825dfa2-63b8-11e5-9c29-e31a7ace4f72" src="https://cloud.githubusercontent.com/assets/69156/10119837/abfd5bf8-6470-11e5-83c2-220a80d6d31e.png">

**Comment by desandro** [comment]
Fixed in SHA: 949c42caaf3771d140e7e5f6ee6e5e1ff025fb3e

**Comment by chriscoyier** [comment]
David fixed
