### ISSUE TITLE
Radio buttons on giant search modal are clipped by like... 1 pixel

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#150]
![screen shot 2015-10-01 at 4 43 43 pm 2](https://cloud.githubusercontent.com/assets/8040471/10236586/25b44cce-685c-11e5-8df7-678cf3190e3f.png)

![screen shot 2015-10-01 at 4 45 14 pm](https://cloud.githubusercontent.com/assets/8040471/10236587/28a9bec8-685c-11e5-880a-fd1fb264c9da.png)

Clearly makes the app unusable 😒

**Comment by chriscoyier** [comment]
good eye, fixing!
