### ISSUE TITLE
Old "PRO" badge on documentation page

### ISSUE THREAD

**Issue by postleonardo** [CodePen/redesign#157]
How it's on the documentation page
![screen shot 2015-10-01 at 10 55 41 pm](https://cloud.githubusercontent.com/assets/8656436/10238002/de3adb04-688f-11e5-9b4f-904eaf14b973.png)

How it's on the other pages
![screen shot 2015-10-01 at 10 56 32 pm](https://cloud.githubusercontent.com/assets/8656436/10238009/04e56c4c-6890-11e5-9f47-3e121649c261.png)

**Comment by chriscoyier** [comment]
Ah yes! This is a problem, but also is going to fall under the umbrella of redesigning the entire blog/docs/podcast/meetups/store area that we need to do. For this launch, we just kinda make the header and the footer look the same. But we need to totally overhaul it to get it inline with the new design and we'll make a lot of stuff match when we do that.

**Comment by postleonardo** [comment]
@chriscoyier cool!

**Comment by chriscoyier** [comment]
fixing today
