### ISSUE TITLE
Error thrown when embedding forked pens

### ISSUE THREAD

**Issue by postleonardo** [CodePen/redesign#158]
I don't have any forked pens - not sure if that's why the error is being thrown. But I'm getting the generic "Uh oh, something went wrong" error when trying to embed forked pens.

![screen shot 2015-10-01 at 11 02 03 pm](https://cloud.githubusercontent.com/assets/8656436/10238090/c3aa1650-6890-11e5-9baa-34dd9a8a9bb2.png)

**Comment by quezo** [comment]
Thanks for reporting this bug. It's fixed now.
