### ISSUE TITLE
Love icon gets cut on the third click

### ISSUE THREAD

**Issue by postleonardo** [CodePen/redesign#160]
![screen shot 2015-10-01 at 11 16 27 pm 1](https://cloud.githubusercontent.com/assets/8656436/10238188/bb01125e-6892-11e5-845e-e9e9f00a3540.png)

When clicking for the third time on the hear icon the effect gets cut

**Comment by chriscoyier** [comment]
Yes I see what you mean! Fixing in next deploy.
