### ISSUE TITLE
Wrong alignment in the sharing menu

### ISSUE THREAD

**Issue by shadeed** [CodePen/redesign#162]
The input field and button are misaligned..
<img width="236" alt="screen shot 2015-10-02 at 6 32 58 am" src="https://cloud.githubusercontent.com/assets/8038659/10239002/81b8f52e-68cf-11e5-9455-c24358cb68a6.png">

**Comment by chriscoyier** [comment]
ah yes good eye. Class case of fix one spacing issue and cause another. Fixing in next deplay.
