### ISSUE TITLE
`picked pens` on homepage show incorrect image

### ISSUE THREAD

**Issue by peter-mouland** [CodePen/redesign#168]
On the homepage, the pen title, description and image matched.
when clicking and viewing a pen, going back (using the browser button) would mis-match the titles with images.

*This happened one and I am unable to replicate this again*

**expected view**
![screen shot 2015-10-02 at 11 07 46 am](https://cloud.githubusercontent.com/assets/1727939/10244249/dea71196-68f5-11e5-970b-19e0dcb5486b.png)

**actual view**
*is that an advert sneaking in??*

![screen shot 2015-10-02 at 11 02 34 am](https://cloud.githubusercontent.com/assets/1727939/10244201/9b9be6d8-68f5-11e5-87e5-b969b56ab1d8.png)

**Comment by chriscoyier** [comment]
Very weird bug. Tracking here: https://github.com/CodePen/redesign/issues/90
