### ISSUE TITLE
can't tab or enter on firefox

### ISSUE THREAD

**Issue by Haroenv** [CodePen/redesign#169]
on Windows 10

**Comment by quezo** [comment]
@Haroenv Is this in the editor view? Can you send me a link to the URL where it happens?

**Comment by Haroenv** [comment]
Was in the editor view, can't reproduce right now because it was on a school computer. It was on every pen. I think it must have been a quite recent version of FF.

**Comment by chriscoyier** [comment]
I fired up Windows 10 / Firefox and it seemed OK to me. See: http://d.pr/i/15mWu/3JvUjDVx 

Can you try a different computer at school and let us know if it's replicable on multiple machines? Closing for now as it doesn't seem to be a widespread or reproducible bug.

**Comment by Haroenv** [comment]
Ill try to see if I can reproduce next week
