### ISSUE TITLE
It's not clear what's clickable/tappable

### ISSUE THREAD

**Issue by tobireif** [CodePen/redesign#170]
For example on http://codepen.io/TobiReif/ , there's the "@TobiReif" in the center, it's not a link.
But then there's the other "@TobiReif", which is a link (Twitter).

It would be great if (throughout the whole site) every link would be styled/recognizable as such (eg underlined).

**Comment by chriscoyier** [comment]
Ah yes I see! We manipulate that Twitter link in a weird way. We just just leave that link alone and let it say "twitter.com".

**Comment by tobireif** [comment]
Instead of current code
```
<a href="https://twitter.com/TobiReif" target="_blank" id="profile-link-2">
  @TobiReif
</a>
```
I'd do eg
```
<a href="https://twitter.com/TobiReif" target="_blank" id="profile-link-2">
  twitter.com/TobiReif
</a>
```

Link text "twitter.com/Name" would be clearer / more specific than just "twitter.com".

And the "@Name" text at the top of the page would stay Codepen-specific / wouln't be confused with the Twitter "@Name". (Both user names might consist of the the exact same character string.)

**Comment by quezo** [comment]
We'll stop giving special treatement to twitter links

**Comment by tobireif** [comment]
Can you elaborate?

The issue I reported is: It's not clear what's clickable/tappable.

**Comment by quezo** [comment]
The links will now appear as links instead of a special @username that links to twitter. Fix is going up now.

**Comment by tobireif** [comment]
Checked it out on http://codepen.io/TobiReif/ , all good now. Thanks!
