### ISSUE TITLE
activity menu showing even after removing it.

### ISSUE THREAD

**Issue by oliverholretz** [CodePen/redesign#171]
when i click on the activity menu and then click on the profile menu i can't click the profile menus links, but instead i get the activity menu link, even though they're invisible(with visibility: none).

look in the bottom left corner for the links that show up

![nimbus-record-video 4](https://cloud.githubusercontent.com/assets/10248190/10245653/dedc676a-6909-11e5-9a79-98e3f8d34b7b.gif)

**Comment by chriscoyier** [comment]
We've been struggling with this a bit. Trying to get too fancy with visibility stuff. Deploying a fix for this now. We really need to revisit the whole system of dropdowns though.
