### ISSUE TITLE
Next button should go to the top of the page

### ISSUE THREAD

**Issue by msamways** [CodePen/redesign#176]
When I click the next/prev buttons it shows the bottom of the next/prev page. Would be more intuitive if it went to the top cause I'm lazy and have to scroll up haha If you need more details, lets me know.

**Comment by yukulele** [comment]
:+1:

**Comment by quezo** [comment]
I'm lazy too. I added some logic so that if you can't see the top of the grid we send you back tot he top. Thanks for reporting this.

**Comment by msamways** [comment]
Epic!!
