### ISSUE TITLE
Wrong previews showing on pens

### ISSUE THREAD

**Issue by drewgHF** [CodePen/redesign#177]
When viewing a pen, if I hit the back button on the browser, the previews on pens seem to shift one pen off. 
<img width="1197" alt="screen shot 2015-10-02 at 12 19 21 pm" src="https://cloud.githubusercontent.com/assets/13109106/10252891/d863a484-68ff-11e5-96ec-cac775e7a557.png">

**Comment by chriscoyier** [comment]
Thanks! Lots of people are seeing this, so it's definitely a bug. We're tracking it here: https://github.com/CodePen/redesign/issues/90
