### ISSUE TITLE
Prefill Request not using "editors" option.

### ISSUE THREAD

**Issue by MichelSimonot** [CodePen/redesign#178]
Since the redesign, my Prefill Requests have not been using the "editors" option and opening with the panes I want. All the panes are opened when loaded as if there was no option supplied. I was hoping https://github.com/CodePen/redesign/issues/112 would help shed some light, but that was fixed.

Is the POST to Prefill API the same as before the redesign, or is the documentation still being updated?

Here's what I'm trying to do:
``` javascript
{
    'title': 'Pen Title',
    'html': '<!-- Pane is open. -->',
    'css': '/* Pane is closed. */',
    'js': '/** Pane is open. */',
    'editors': '101'
}
```

Thanks.

**Comment by chriscoyier** [comment]
Marc-Andre Lafortune in Support 3858 mentioned this too, update him when fixed.

**Comment by chriscoyier** [comment]
Moving here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/14
