### ISSUE TITLE
Script sometimes fails to load on profile tabs.

### ISSUE THREAD

**Issue by Reklino** [CodePen/redesign#179]
```
GET
http://assets.codepen.io/assets/profile/pens/index-47f833c9ff80ea880883dbb74641473b.js 
codepen.io/:963
```
I am getting this error every once in a while when swapping between the popular, public, and private tabs on the user profile page. When I get this error, the associated pens fail to load.

**Comment by quezo** [comment]
I think this may have been an issue with our deployment. I pushed again. Reopen this if you still encounter the error.
