### ISSUE TITLE
Anon users have no "Change View" button 

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#180]
Without this button, anon users have no access to the "Editor Layout" switcher or the CrossBrowserTesting link

![screenshot 2015-10-02 14 57 02](https://cloud.githubusercontent.com/assets/456844/10255076/dbb0c70a-6915-11e5-9fe6-9f7eb3b5e5d0.png)

**Comment by quezo** [comment]
Going up with next push.
