### ISSUE TITLE
Close button on pen settings is hard to find

### ISSUE THREAD

**Issue by miguelsolorio** [CodePen/redesign#187]
It was bugging me that I couldn't find a way to close the "pen settings" modal window, so I kept hitting the gear icon in the background to dismiss it the window. A few days later I realized there was a giant "Close" button below the modal window (I usually block everything outside of the window), not a place one would expect a close button (they're typically in the top right or left side), especially since all actions take place inside of the modal window. Even after realizing where the close button was re-located, I still looked in the top-right corner and had to remember where it was at. Thought i'd record this feedback in case others had issues.

Example: http://d.pr/i/1kwQE
![Example](http://d.pr/i/1kwQE+)

**Comment by thebabydino** [comment]
I've also had trouble with this on my own pens.

And I've checked the template checkbox by accident a few times because that's where the private checkbox used to be...

**Comment by chriscoyier** [comment]
We're incrementally trying to make this better. One thing we've done now is to open the overlay behind it so the button stands out a bit more, and you can once again click-off to close it. We have a few more ideas as well.
