### ISSUE TITLE
New Template doesn't look like its clickable

### ISSUE THREAD

**Issue by rkhayat** [CodePen/redesign#192]
{title} The 'new Template' looks like text, and doesn't look like its clickable. I feel like a lot of new users will miss it. I am referring to "You have no templates yet. Let's go make one!"

**Comment by chriscoyier** [comment]
We hear you. It's consistent with the style in 1) the view switcher in the editor 2) the user dropdown 3) the template menu where there are templates there 4) the export menu in the editor 5) the share menu in the editor ... so I think for now we'll keep it. I could see mayyyybe a button style if we get more feedback that people aren't getting it.
