### ISSUE TITLE
Restoring (un-collapsing) a collapsed editor is confusing

### ISSUE THREAD

**Issue by hudakdidit** [CodePen/redesign#195]
![a_pen_by_jonathan_hudak](https://cloud.githubusercontent.com/assets/1223821/10265338/09171e16-69e2-11e5-877c-96a23ed3e6f3.jpg)

There used to be buttons along the bottom to restore(un-collapse) the  HTML/JS/CSS editors, but those no longer seem to be present. It seems, currently you are able to drag a collapsed editor window up and reveal it again, but this isn't intuitive IMO. The X button toggling to a plus button rather than a deactivated state would be a much more clear way to expand the editor window.

Also, I love codepen, and the redesign overall is fantastic!

**Comment by chriscoyier** [comment]
> There used to be buttons along the bottom to restore(un-collapse) the HTML/JS/CSS editors

Those were removed intentionally. It was a weird bit of unconnected UI I was glad to see leave =)

> The X button toggling to a plus button rather than a deactivated state

I could see that... although it only applies when the editor is in a **side** layout. Plus we'd have to decide what the plus would actually do...

1) maximize?
2) return to what size the editor was before it was closed?
3) split the difference between the other open editors?

I'm going to close this since I wouldn't consider it a bug - and let @desandro weigh in.

**Comment by hudakdidit** [comment]
@chriscoyier agreed this is not a bug, and also I agree the UI was unconnected living in the footer.

Perhaps this is just specific to the way I use the editors along the right side, but I put together a quick pen of what I mean. http://codepen.io/hudakdidit/pen/XmMQrv I'm sure there are countless other considerations I'm not taking into account.

Regardless, thanks for the reply!

**Comment by desandro** [comment]
>> The X button toggling to a plus button rather than a deactivated state
> 
> I could see that... although it only applies when the editor is in a side layout. 

I like this idea as well. I'll play around with the concept to see if its worth adding.

> Plus we'd have to decide what the plus would actually do...

FYI, current behavior is to split the difference.

**Comment by yukulele** [comment]
My suggestion:
double-click on expended editor to restore initial editors size (each 3 editors size = 33%)

**Comment by desandro** [comment]
Thanks for your suggestion. We've added double-click to reset sizes. You'll see this feature in the next day or so.
