### ISSUE TITLE
Fix Firefox Animation Stopping in the Grid

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#198]
from @ge1doot:

---

> Firefox does not stop the pens in grid mode.
> There is a bug before in your code that break the script (but it fails silently since window.onerror is also disabled).

> Instead of :

```
   if (typeof (speechSynthesis.speak) != "undefined") {
     speechSynthesis.speak = function() {return false;};
   }
```

That gives this error:

> ReferenceError: speechSynthesis is not defined

You should probably do this:    

```
    if (typeof (speechSynthesis) != "undefined") {
     speechSynthesis.speak = function() {return false;};
   }
```

**Comment by paulirish** [comment]
true. the current detect isn't so safe.

current JS:
```js
if (typeof (speechSynthesis.speak) != "undefined") {
  speechSynthesis.speak = function() {return false;};
}
```


better:
```js
if (!("speechSynthesis" in window)) window.speechSynthesis = {};
if (!("speak" in speechSynthesis)) speechSynthesis.speak = function() { return false; }
```

**Comment by tholman** [comment]
Thanks @paulirish ... fixed now!
