### ISSUE TITLE
Formatting issue in comment headers on iPhone/iOS

### ISSUE THREAD

**Issue by ge1doot** [CodePen/redesign#201]
![img_2210](https://cloud.githubusercontent.com/assets/3667777/10269523/eab990c6-6ada-11e5-8651-19679d8a9767.PNG)

**Comment by chriscoyier** [comment]
weird I thought I had this fixed... maybe you have cached version somehow, or, the user has applied custom CSS to the post that is causing this.

<img width="460" alt="screen shot 2015-10-05 at 10 11 35 am" src="https://cloud.githubusercontent.com/assets/69156/10284429/9a4d43e8-6b49-11e5-90f4-340690fa196e.png">

I can re-open if you can send me link where it still does this.

**Comment by ge1doot** [comment]
Well... a real iPhone (not an emulator), a real user (me), the latest iOS 9.0.2, not a cache issue, not a custom CSS thing, every pen comment, every pen, logged (from Safari) or not logged (from the twitter UIWebView for example)...
