### ISSUE TITLE
Pen thumbnails move +1 when you go back from single pen view

### ISSUE THREAD

**Issue by remeritus** [CodePen/redesign#202]
This happened to me multiple times and basically on any subpage that deals with displaying pen thumbnails. Somehow content of an ad gets pulled into the first pen's thumbnail and the rest of them jump to next ones. 
![wierd](https://cloud.githubusercontent.com/assets/7386641/10269573/45af1c2a-6adc-11e5-8fa8-172e9e8c09bb.gif)

**Comment by remeritus** [comment]
I've just found that this is already an issues

**Comment by chriscoyier** [comment]
it's this weird chrome back button iframe bug. Also related to this https://github.com/CodePen/redesign/issues/90 so tracking there.
