### ISSUE TITLE
Template checkbox's help tooltip hides under left side panel

### ISSUE THREAD

**Issue by krish4u** [CodePen/redesign#206]
Create a newpen --> settings --> mouseover the template's helper ( the ? mark sign ) the tool tip hides under the left side panel. 

browser : chrome 45.0.2454.101 m

![codepen issue](https://cloud.githubusercontent.com/assets/5724658/10274016/6e2577c4-6b56-11e5-8a10-7e7c4e99014c.jpg)

**Comment by kjohnson** [comment]
Same. Bump.
![screenshot 2015-10-05 10 53 33](https://cloud.githubusercontent.com/assets/10858303/10283835/70e508f0-6b4f-11e5-8c4b-6ed2365f1777.png)

**Comment by chriscoyier** [comment]
Fixing in next deploy. Thanks both of ya!

**Comment by krish4u** [comment]
the question mark moves to the right side but the tooltip overflows the window and adding a scroll bar.
![codepen issue 2](https://cloud.githubusercontent.com/assets/5724658/10299841/d64a2fdc-6c0c-11e5-91a6-27f71f3094ce.jpg)

**Comment by mariemosley** [comment]
This one is misbehaving in a different way now, it hides in the other direction. Member submitted this gif by email, I can reproduce in all OSX browsers: 
 
![abouttemplates-1](https://cloud.githubusercontent.com/assets/456844/10313357/37e68c80-6c1d-11e5-81c9-829fc4a8959a.gif)
