### ISSUE TITLE
blog post overflow

### ISSUE THREAD

**Issue by oliverholretz** [CodePen/redesign#207]
i found a block that have images overflowing content area
[http://codepen.io/tomhodgins/post/writing-html-on-android](http://codepen.io/tomhodgins/post/writing-html-on-android)
![screenshot-codepen io 2015-10-05 13-50-35](https://cloud.githubusercontent.com/assets/10248190/10279795/dacf7c00-6b68-11e5-91b9-1f8c86247113.png)

**Comment by chriscoyier** [comment]
Looks like that's fixed. The author is doing some fancy layout and custom styling of their own here.
