### ISSUE TITLE
user/tag/tag-name pages 404

### ISSUE THREAD

**Issue by desandro** [CodePen/redesign#208]
Are user tag pages still a thing? My previous links are 404ing:

http://codepen.io/desandro/tag/isotope-docs
http://codepen.io/desandro/tag/masonry-docs
http://codepen.io/desandro/tag/packery-docs
http://codepen.io/desandro/tag/flickity-docs

**Comment by quezo** [comment]
New URL and we forgot to redirect the old URL. It's fixed now.
