### ISSUE TITLE
Be More Aggressive with Excerpts

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#21]
![3aeed530-5c88-11e5-85ba-345d9446beaf](https://cloud.githubusercontent.com/assets/69156/10120219/e298c478-647e-11e5-801f-aafd2d508024.png)

1. remove links that are just #links
2. strip `<hr>` probably
3. strip empty elements. (I saw a post with just `<p><br></p>`, can we strip that?) -- maybe strip `<br>`s first, then empty elements.
4. strip embeds (e.g. `[[[pen slug-hash='XmreZx' height='300'...`) or replace with title/link?
5. bold headers in addition to making them just `<p>`s? or just strip them?

**Comment by quezo** [comment]
So this is actually unnecessary. That first column was showing a long summary while the second two are showing a short summary. I fixed it in this next push to all show a short summary.

http://d.pr/i/KHpQ/14Rrb0Nc

It has to do with the logic around the posts/single-post.html.erb file where it tries to show a long summary based on the index of the loop.

Reopen if you still don't like the long summary.
