### ISSUE TITLE
Searching Pens from User Page Defaults to My Pens

### ISSUE THREAD

**Issue by jackrugile** [CodePen/redesign#212]
I am trying to search with a keyword of the pens from a specific user. For example, on GreenSock's page, I'd like to search through their pens based on a keyword, such as "svg". When I enter my search though, it brings me to results for my pens.

I am getting this behavior from the search box on a user page, here for example: http://codepen.io/GreenSock/

![screen shot 2015-10-05 at 11 47 02 am](https://cloud.githubusercontent.com/assets/726153/10288566/d1aa6aa2-6b56-11e5-890d-886e75ce59e4.png)

I expect typing a query into the "Search GreenSock" field would limit the results to their pens, but it switches over to the "mine" filter when I search.

Let me know if you need any more details. Thanks!

**Comment by tholman** [comment]
Kapow, fixed.
