### ISSUE TITLE
Editor mode: Inability to completely hide code panels is a drawback in my view

### ISSUE THREAD

**Issue by dmitrynizh** [CodePen/redesign#213]
Hi, 

I'm unable to fully hide the HTML & CSS panels in the Editor mode.
Before the Oct 2015 UI changes, one could completely hide up to 2 out of 3 code panels using corresponding  toggle buttons located in the bottom right corner or with the 'x' buttons on each.  This was what made codepen.io notably different from other code playgrounds. In the new UI, the toggle buttons are, alas, gone, and clicking 'x' (when active) results in the panels remaining in minimized form, consuming lots of screen real estate. To me this  is a very serious usability regression and a serious shortcoming of the new redesign. Is there a way to completely hide the panels in the new UI? Could it be fixed in the near future?

**Comment by desandro** [comment]
Thanks for this feedback. Yes, the new editor design does not allow you to completely hide panels. Here's why we did it:

+ Previous design had separated UI elements. You could close a panel via a button in it, but to re-open it, you had to use a separate button row in the footer. They were in a different place, small, and hard-to-find.
+ Keeping persistent area for panels is a usability win. You can immediately see which panel is open and which is closed. There is a persistent target available, making it easy to drag open. You can now drag close a panel, so we need that target.

It's a worthwhile trade-off. Using the editors is simpler and it only cost us 70px of additional chrome.

**Comment by dmitrynizh** [comment]
Hi David, 
Thanks for getting back and discussing the issue with me and also thanks for providing the detailed reasons on why the buttons are gone. I understand your rationale, however  my preferences are just the opposite of what you have described. More, I disagree that buttons were hard to find I respectfully disagree with every single point you mentioned in support of the change. I liked the old UI design and I hate the new design. I lost about 10 lines of editable code  space, it is more than enough to be the reason to stop using your tool. Many if not the majority of JS codes will agree with me. Secret to keeping your user base? Make 'm happy, David. I suggest the person in charge in your team to please consider finding a way to have the mode I'm missing as a configuration option. 
Regards, 
Dmitry
 

Date: Tue, 6 Oct 2015 07:28:26 -0700
