### ISSUE TITLE
Free Trial link 404s from /pro

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#214]
Submitted by email:

from http://codepen.io/pro/
-> Free Trial -> &lt;p>We offer free fourteen day trials of CodePen PRO if you'd like to try it out.&lt;/p>

http://codepen.io/promo/free-trial -> redirecting to https://codepen.io/promo/free-trial - 404

**Comment by chriscoyier** [comment]
This is only happening if you are LOGGED OUT.

**Comment by ricardozea** [comment]
I was logged in and was able to see it tho.

**Comment by helmutgranda** [comment]
Nov 9. Still happening logged in or out.
