### ISSUE TITLE
Settings Help ToolTip Hides

### ISSUE THREAD

**Issue by krish4u** [CodePen/redesign#216]
the question mark moves to the right side but the tooltip overflows the window and adding a scroll bar.
![codepen issue 2](https://cloud.githubusercontent.com/assets/5724658/10299841/d64a2fdc-6c0c-11e5-91a6-27f71f3094ce.jpg)

**Comment by chriscoyier** [comment]
fixed

**Comment by krish4u** [comment]
looks great.
