### ISSUE TITLE
Inline code isn't styled in markdown comments on pens

### ISSUE THREAD

**Issue by chasebank** [CodePen/redesign#217]
I can't remember if this was styled before, but it isn't now, aside from font.

Syntax highlighting would be fancy, but just some added `visible separation` from plain text would help.

maybe something like
```css
background: #515156;
padding: 0 .2rem;
```

My comment here has inline code: http://codepen.io/nathanlong/details/ioGbv/

**Comment by chriscoyier** [comment]
I gave 'er a little loving

![screen shot 2015-10-08 at 5 44 03 pm](https://cloud.githubusercontent.com/assets/69156/10381912/3055433a-6de4-11e5-9e17-eff94c713547.png)
