### ISSUE TITLE
Change View Learn-More Links Do Nothing

### ISSUE THREAD

**Issue by kaleb** [CodePen/redesign#219]
Observed:

When I click on the *Change View* button, I see a list of views. Each view has a `span.learn-more` question mark icon to the right of it. Hovering over the icon does nothing. Clicking on the icon behaves as if I just clicked on the view-name.

Expected:

Either hovering over the icon would display a tooltip or clicking on the icon would take me to a page describing the view.

Luckily I could get to the view's documentation by copying the value of the `[data-href]` attribute.

**Comment by chriscoyier** [comment]
Weird. I tried a couple browsers and it seems OK: http://d.pr/v/14DvL/ewqN51aC

I can re-open if you can hit me with some more details.
