### ISSUE TITLE
Search doesn't prompt with keyboard on mobile

### ISSUE THREAD

**Issue by remeritus** [CodePen/redesign#221]
Hi Guys,
I am on iOS and when i hit on search icon i get this search dropdown with radio buttons but no text input for my search => hence keyboard doesn't show up and i can't search  :)
![image](https://cloud.githubusercontent.com/assets/7386641/10323005/c0fa53f4-6c80-11e5-9c75-38e2d21c3267.png)

**Comment by ge1doot** [comment]
Same for me... until I understand the secret textfield was the BIG "Search" title itself... strange counter intuitive design...

**Comment by remeritus** [comment]
Yep now I've also cracked it, somehow it was obvious on desktop but does't teally ring the bell on mobile, i would sugest that on mobile the field gets focused right away because I think i am not the only one who is used to click on magnifying glass and expect the keyboard to show up :)

**Comment by remeritus** [comment]
I've just tested search in Chrome on iOS and search dialog doesn't even come up. Icon highlights and nothing else happens than when i click on my avatar 'personal menu' shows up and also search dialog.

**Comment by chriscoyier** [comment]
Autofocusing the search field seems like the easy win here. Weird that we don't.

**Comment by chriscoyier** [comment]
Unfortunately what seemed like an easy win is not easy at all. Forcing focus on an input is SUPER hard on iOS.

See:

- https://www.quora.com/Mobile-Safari-iPhone-or-iPad-with-JavaScript-how-can-I-launch-the-on-screen-keyboard
- http://stackoverflow.com/questions/18728166/programatically-focus-on-next-input-field-in-mobile-safari
- https://github.com/jquery/jquery-mobile/issues/3016
- http://stackoverflow.com/questions/979309/how-do-i-focus-an-html-text-field-on-an-iphone-causing-the-keyboard-to-come-up
- http://stackoverflow.com/questions/18519743/how-do-i-force-focus-on-a-texfield-when-the-dom-is-ready-in-ios

I've tried a bunch of stuff and got nuthin' 

We might need to punt on this for now and think about it from a UI perspective.
