### ISSUE TITLE
Unable to write in editor on Windows 10 Phone 

### ISSUE THREAD

**Issue by oliverholretz** [CodePen/redesign#222]
I am not been able to get the keyboard to show when i have try to edit a pen on my phone, i can see when i tap the code that i focus the code, but no keyboard comes up.

**Comment by chriscoyier** [comment]
Can you try going here and seeing if it opens in this editor? http://codemirror.net/

**Comment by oliverholretz** [comment]
Neither there, but then i'm guessing it's their editor that's the problem.

**Comment by chriscoyier** [comment]
We need to punt that over to https://github.com/codemirror/codemirror/issues - if CodeMirror starts supporting it, then we do too automatically =)
