### ISSUE TITLE
Menus don't collapse when tap away

### ISSUE THREAD

**Issue by remeritus** [CodePen/redesign#223]
While on mobile if i click on menu it drops down, if i click on my profile right after it drops down, if i click on search right after it will also drop down resulting in pure chaoss on the screen :)
![image](https://cloud.githubusercontent.com/assets/7386641/10323807/c301102a-6c85-11e5-9b70-a9018e95bed6.png)
![image](https://cloud.githubusercontent.com/assets/7386641/10323808/c3245260-6c85-11e5-8ade-bbaa6d8bb5ef.png)

**Comment by chriscoyier** [comment]
Verified.

1. Opening Search should close any dropdown
2. Opening any other dropdown should close other dropdowns (weird that it doesn't now, it should, and does on desktop, but doesn't on mobile)
3. Search should auto-focus search field as well.
