### ISSUE TITLE
Comment/description modal animation is inconsistent

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#226]
I think this has actually been happening since before the redesign but when you open the comment/description modal for the first time when viewing a Pen it rapidly animates from basically open to closed to open, and then toggles as expected afterward. Preeeeetty hard to see in the gif (sorry!) but hopefully it helps illustrate things.

![titld0q6fb](https://cloud.githubusercontent.com/assets/8040471/10326124/4acab356-6c4c-11e5-89c1-97c6dac00799.gif)

**Comment by alexzaworski** [comment]
Hmm also some of the text on that comment box in the gif is overlapping. Just noticed that, not sure if you guys care to support that— window was tiny to keep gif size down.

**Comment by chriscoyier** [comment]
Confirmed all, will fix tomorrow.

**Comment by chriscoyier** [comment]
fixed in next deploy
