### ISSUE TITLE
[Heat Holders Online Store] Remain on product page after adding item to cart

### ISSUE THREAD

**Issue by mattpoto** [CodePen/redesign#227]
[Internal dashboard link](https://app.shopify.com/services/internal/shops/1161462)

Login: https://heatholdersshop.myshopify.com/admin/staff

Design time used: 0 minutes

---

If you visit the merchant's store and add a product to your cart you will immediately be brought to the cart page:

https://screenshot.click/2015-10-06_17-00-21_0_edited.mp4

The merchant would like the customer to remain on the product page after adding a product to their cart.

**Comment by chriscoyier** [comment]
wrong repo I think ;)
