### ISSUE TITLE
Broken editor layout after clicking Fork

### ISSUE THREAD

**Issue by shubhra14** [CodePen/redesign#228]
I experienced a bug I guess, I clicked fork on a pen. However, everything was normal when I reloaded the window.

![issue](https://cloud.githubusercontent.com/assets/5490862/10326424/9501ffc6-6cb8-11e5-8d0b-e7b080d1c1b1.jpg)

**Comment by shubhra14** [comment]
Reloaded the window again

![issue1](https://cloud.githubusercontent.com/assets/5490862/10326490/6e28befc-6cb9-11e5-9090-3d2b63ae013f.jpg)

And again

![issue2](https://cloud.githubusercontent.com/assets/5490862/10326520/d5a7553e-6cb9-11e5-9edd-2c8bcb93be11.jpg)

**Comment by chriscoyier** [comment]
I think you just caught us RIGHT at the end of a deploy
