### ISSUE TITLE
Preview resizing doesn't work as expected

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#230]
Members are having difficulty testing responsive designs because the preview pane only resizes as expected in one direction. Screencast demonstrating the issue: http://d.pr/v/10VVn/4vFJhWWN

**Comment by bekahsealey** [comment]
I ran into this problem today, trying to test a flexbox layout. Wasn't sure if it was just me. This is the pen I was creating: http://codepen.io/bekahsealey/pen/ojWRve.

**Comment by TropicalHenry** [comment]
Hey, im having the same issue. I have tried 3 different browsers on two different computers. The issue is effecting all pens that i view or create and its been this way since yesterday morning.

**Comment by TropicalHenry** [comment]
Also im getting problems resizing the preview pane from both sides. The pen content just gets stuck at 1000px even when the browser is smaller.
If i go to Change View > Details View then the pens do become responsive again.
Maybe that helps.....

**Comment by chriscoyier** [comment]
Got a fix for this going out now, sorry gang.
