### ISSUE TITLE
"Search Your Pens" from collection searches entirety of CodePen if you press enter again

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#231]
Steps to reproduce:

1. Search using the "Search Your Pens" input on collection page, results will be correct
2. From search results, press enter again. Results will be from all of CodePen

![7ecaq2aznz](https://cloud.githubusercontent.com/assets/8040471/10344848/7d05167a-6cda-11e5-9d35-9383b59f0d3b.gif)

**Comment by chriscoyier** [comment]
Tim fixed this.
