### ISSUE TITLE
Whitespace above #promo-footer is to big at /collections/

### ISSUE THREAD

**Issue by remeritus** [CodePen/redesign#239]
Whitespace above #promo-footer seems to be quite inconsistent depending on which page you are in collections/picks/ it becomes quite wild :)

homepage:
![home](https://cloud.githubusercontent.com/assets/7386641/10363522/3ec8263c-6db5-11e5-9abc-0671093e269f.png)

collections:
![colections](https://cloud.githubusercontent.com/assets/7386641/10363542/5bbc7784-6db5-11e5-9331-b1f564e276e7.png)

on mobile it results into over 50% of nothingness:

![image1](https://cloud.githubusercontent.com/assets/7386641/10363591/aec131ae-6db5-11e5-994d-8185ce68f17d.PNG)

**Comment by chriscoyier** [comment]
Think I got this cleaned up, fixing going out later today.
