### ISSUE TITLE
Editing the Showcase

### ISSUE THREAD

**Issue by tobireif** [CodePen/redesign#240]
On http://codepen.io/TobiReif/organize ,
after I dragged several pens to the trash icon
(in order to remove them from the "Showcase" page
http://codepen.io/TobiReif/ ),
they keep appearing on the showcase page.

On the showcase page I want only the pens to appear that I had dragged into the showcase area - the rest of the cells should be blank/black.

I don't want any pens to appear on the showcase page that I had dragged to the trash area.

Perhaps as account-wide setting?

**Comment by chriscoyier** [comment]
I think what might be happening is when you have blanks in your Organize area, we fill those blanks in with your algorithmically most popular other Pens. So even though you've trashed one, if there is a blank and that Pen happened to be pretty popular, it will come back into that blank.

To fix, fill up all blanks =)

**Comment by tobireif** [comment]
Yes, and until I filled all blanks with showcase-worthy pens, I'd like to set the blanks to be empty, in order to not showcase pens that weren't meant to be showcased (public but not for the showcase). Could be a new setting instead of a change (so that those users who like the current way aren't affected).

Please reconsider :)
