### ISSUE TITLE
Error when trying to switch between user profiles 

### ISSUE THREAD

**Issue by robinrendle** [CodePen/redesign#243]
When I hit the _Switch to you_ button in the Profile menu I get this error:  

<img width="602" alt="screenshot 2015-10-08 15 47 41" src="https://cloud.githubusercontent.com/assets/1900676/10373438/56ddccce-6de5-11e5-8e1b-9565cd1a82ff.png">

**Comment by chriscoyier** [comment]
Yeah looks like a regression :( tracking here https://github.com/CodePen/redesign/issues/242
