### ISSUE TITLE
Enhancement/feature request: make title editable

### ISSUE THREAD

**Issue by KuraFire** [CodePen/redesign#244]
The title of a pen is shown clearly in the top left corner, but it's not editable there. However, when you edit it in the Settings modal dialog, it does update immediately. 

Would be great if we could just click the title to edit it in place, and have the hash of the pen itself serve/act as a placeholder attribute when you click it the first time.

**Comment by chriscoyier** [comment]
I hear you!

It's a possibility we add an edit button or something. Click-to-edit might work if we have some kind of UI that suggests you can do that and that makes sense why you can't do it on (for instance) a Pen you don't own. Click-to-edit just isn't a design pattern we've ever used before on CodePen so I don't wanna just slap it in without considering it a bunch and where else we might use it. 

Probably will just need to digest a while. Closing for now as not really a bug.
