### ISSUE TITLE
organize showcase order incorrect

### ISSUE THREAD

**Issue by pixelass** [CodePen/redesign#247]
currently when organizing the showcase the order is incorrect or wrong pens are shown. So each time I want to change my showcase I have to make sure I change every tile.

<img width="1212" alt="screen shot 2015-10-08 at 9 07 55 pm" src="https://cloud.githubusercontent.com/assets/1148334/10385657/dfc68c04-6e00-11e5-81e8-90f9ac99491e.png">
<img width="694" alt="screen shot 2015-10-08 at 9 07 43 pm" src="https://cloud.githubusercontent.com/assets/1148334/10385658/dfc6d36c-6e00-11e5-8a1b-7080821f2cc0.png">

**Comment by pixelass** [comment]
I cannot reproduce wrong pens anymore but the order is definitely wrong.

On the first days after the relaunch they would change (to the correct ones) when you dragged and dropped them in the same box (lift and let go) but that doesn't happen anymore either.

**Comment by tholman** [comment]
I can't seem to reproduce this one any more. I think it might have been tied in with a different bug thats been fixed now. (to do with `iframes` needing id's)

Although please re-open if its still happening! :dancer:

**Comment by pixelass** [comment]
Sorry .. hate to burst your bubble ;)  @tholman it seems I can't reopen it myself.

![issuecp](https://cloud.githubusercontent.com/assets/1148334/10711158/bda41f00-7a27-11e5-83c9-6203f9cacdf9.gif)

**Comment by chriscoyier** [comment]
Support email 3806 also confirms it's still a bug.

**Comment by tholman** [comment]
:D Joy!

**Comment by chriscoyier** [comment]
Moved here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/12
