### ISSUE TITLE
Give more importance to forks

### ISSUE THREAD

**Issue by yukulele** [CodePen/redesign#251]
Forks have a very low visibility.

Some suggestion to give a better visibility to forks:

* alert me by email when someone fork my pen
* show forks on activity page and activity widget
* show forks count on detail page, on "stats" tab (with "views", "comments" and "hearts" counts)
* show forks count on all pen thumbnails (like "views", "comments" and "hearts" counts)
* don't save fork if their is no change (most fork are no differences from original pen)

Other suggestions (more complex):

* add data  comparison (to show what is changed)
* show diff counts on for each forks on forks tab
* order forks by diff count
* allow author to merge changes from a fork

**Comment by mariemosley** [comment]
Thanks for the feedback! We have a lot of these ideas under consideration. I am closing this issue since it's not really a bug, but we hear you :+1:
