### ISSUE TITLE
Save Editor Layouts on profile settings

### ISSUE THREAD

**Issue by yukulele** [CodePen/redesign#258]

**Comment by chriscoyier** [comment]
Like have an option to, say, have the JS editor collapsed by default when you start a new Pen? Possible! If this is a bug, lemme know, otherwise we'll make sure it's on our list of ideas for settings/templates.

**Comment by yukulele** [comment]
No, I speak about codes position (left / top / bottom) it's saved on cookies, I think it should save on profile.

![capture d ecran 2015-10-11 a 21 14 33](https://cloud.githubusercontent.com/assets/347244/10418511/58c7f83c-705d-11e5-9603-b20dc01cf565.png)

for example, I Personally usually use right layout ; when I login on Codepen (on a public computer for example) it load pen with default top layout.
