### ISSUE TITLE
follower links without protocol broken

### ISSUE THREAD

**Issue by pixelass** [CodePen/redesign#259]
When there's no protocol the links direct into a 404. (see image: davidkpiano is hovered)

<img width="695" alt="screen shot 2015-10-10 at 12 04 58 pm" src="https://cloud.githubusercontent.com/assets/1148334/10412848/8e2969f0-6f47-11e5-8737-a1321476313d.png">

**Comment by chriscoyier** [comment]
We are just implementing now some better URL validation for those links. So it should happen less and less, but, there will still be existing URL's that are broken, so....

It's kinda weird that it links to the first URL you put on your profile, or falls back to your profile URL here. So I think I'll just rip out that second URL.
