### ISSUE TITLE
User Search tweaks

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#26]
1. Exact match on name should rank higher.
2. Needs to link to actual profile, not github or whatver.

<img width="1212" alt="screen shot 2015-09-26 at 10 03 57 pm" src="https://cloud.githubusercontent.com/assets/69156/10120760/91bfc09e-649a-11e5-9df3-e8eda63faedc.png">

**Comment by tsabat** [comment]
Fixed #2 
#1 is more tricky.  I'll focus on that more if I can before launch, if not, after.

**Comment by chriscoyier** [comment]
#2 was fixed, #1 should probably be addressed, but it seems to largely work fine and we've gotten zero feedback about it so meh.
