### ISSUE TITLE
Explore collections select input is messed up

### ISSUE THREAD

**Issue by remeritus** [CodePen/redesign#260]
This is /collections/picks/ on mobile (iOS):
![image](https://cloud.githubusercontent.com/assets/7386641/10412850/0810a53a-6f93-11e5-8f75-4655bc64f7fc.jpeg)

**Comment by chriscoyier** [comment]
Ug yeah. This is a weird one that is going to resolve itself I think when this one does: https://github.com/CodePen/redesign/issues/137
