### ISSUE TITLE
link colors in settings

### ISSUE THREAD

**Issue by oliverholretz** [CodePen/redesign#261]
the analyze links in the setting modul in pens has different via link colors on the analyze js and analyze css.

![http://i.imgur.com/xdMirFO.png](http://i.imgur.com/RqBqDD7.png)
![http://i.imgur.com/xdMirFO.png](http://i.imgur.com/xdMirFO.png)

**Comment by chriscoyier** [comment]
good catch.

gosh we need to move those actions out of the settings and into the editor somewhere.
