### ISSUE TITLE
Change from grid to list view can break url

### ISSUE THREAD

**Issue by chasebank** [CodePen/redesign#266]
If a user clicks through additional pages before switching to List View, an error is often displayed

> You haven't built any pens yet.  Go build one!

http://codepen.io/chasebank/pens/public/2/?grid_type=list

I assume List View eventually paginates, but since it shows so many more pens than Grid View, users are likely to hit this error often. Changing the grid should default back to page 1.

The error is also misleading. If someone visits a page # that exceeds the amount of pens, but there are pens, it should redirect to a page with pens (if not the last page with content, at least back to page 1).

**Comment by chriscoyier** [comment]
Good catch here.

I agree that when you switch views it should default back to page 1.

@quezo this is the `grid_url` function I'm pretty sure, just a little logic on which is the active view can fix I think...

Context:

![img](http://d.pr/i/1enpG/5SN2wg3q+)

**Comment by quezo** [comment]
Great catch. This is going up in 10 minutes with next push.
