### ISSUE TITLE
Lists in Pen Descriptions need more spacing

### ISSUE THREAD

**Issue by kevingimbel** [CodePen/redesign#268]
When viewing a Pen's Detail (hovering over the pen preview), and there's a list inside, it is cut off on the left side. A bit of `margin-left` fixes this issue.

![codepen_collection_list_description](https://cloud.githubusercontent.com/assets/2161714/10424432/7277826c-70cf-11e5-9e40-bf86eae3d8f0.png)

**Comment by chriscoyier** [comment]
Good catch! Fixing in the next deploy.
