### ISSUE TITLE
Safari transform anti-alias flicker when dragging editor boxes

### ISSUE THREAD

**Issue by desandro** [CodePen/redesign#270]
[Adam Šír](https://twitter.com/Donuteeze/status/652985467462418432):

> new ui +1 .. but flickering in Safari is not pretty...  solution: transform: translateZ(0);

---

Weird thing is that the header, Fork button, and Settings button flicker, but the rest of the UI does not. I'll have to take a look.

**Comment by adamsir** [comment]
```CSS
body {
   transform: translateZ(0);
}

**Comment by desandro** [comment]
After digging into this issue, I'm afraid we have to close it as `wontfix`.

The issue at hand is the [infamous Safari transform+transition flicker](http://stackoverflow.com/questions/3461441/prevent-flicker-on-webkit-transition-of-webkit-transform). The "solution" provided is to set `-webkit-backface-visibility: hidden` or `transform: translateZ(0)` on flickering or transitioning elements.  I tried several combinations of these techniques, but was not able to completely resolve the issue. Our options were thus:

1. Set `transform: translateZ(0)` on flickering elements. This includes the header and editor code. This removes the flicker by triggering GPU rendering on all affected elements. But, this affects the natural anti-aliasing of fonts.

2. Remove transitions from Safari. Could be done but then we have to do browser sniffing. Also, titles will still run into the buttons when squished.

3. Leave it as is. This bug only occurs in Safari, when you resize the editors in Top layout mode.

 I had hoped to resolve this with a simple CSS fix, but no luck. It's a tough bug that's the fault of the rendering engine, so we don't have good control of it. In good news, this bug was occurring in Chrome but no longer. Hopefully Safari will resolve itself as well.

Thanks again for reporting this bug. We'll keep an eye out for it.
