### ISSUE TITLE
Preview tab of job posting slow/broken

### ISSUE THREAD

**Issue by jplhomer** [CodePen/redesign#273]
In the job posting editor, typing markdown under the Job Description section and then clicking "Preview" results in sometimes nothing, sometimes a small portion of a preview with dark text on a dark background.

Also getting some CORS font issues in the Dev Tools console (see screenshot).

![screen shot 2015-10-12 at 1 11 51 pm](https://cloud.githubusercontent.com/assets/848147/10434996/d2fb795a-70e2-11e5-88ef-560d9f457074.png)

Otherwise, loving the redesign!

**Comment by chriscoyier** [comment]
Great catch. Fixing this in next deploy. The CORS font thing might not be fixed right away, but that's coming soon. @tsabat is on the case on that one as we need it fixed for development reasons too.
