### ISSUE TITLE
Markdown Preview pane for Posts is too tiny to use properly

### ISSUE THREAD

**Issue by davidelrizzo** [CodePen/redesign#274]
For some reason the preview pane iframe is stuck at 300x150px for me.

![screen shot 2015-10-13 at 9 56 12 am](https://cloud.githubusercontent.com/assets/1995386/10441080/aa7bcd00-7190-11e5-9e35-dad0a332685b.png)

**Comment by chriscoyier** [comment]
No idea how that regressed. We're seeing WEIRDLY MANY issues with iframe sizing lately and it's weirding me out. Fixed in next deploy
