### ISSUE TITLE
links in activity dropdown don't work

### ISSUE THREAD

**Issue by pixelass** [CodePen/redesign#275]
clicking links in the notification dropdown does "nothing"

![links broken](https://cloud.githubusercontent.com/assets/1148334/10472503/df321aa0-71d5-11e5-864b-49f036badc0d.gif)

**Comment by tholman** [comment]
Should be fixed :)

**Comment by pixelass** [comment]
yayyyyyyy

**Comment by tholman** [comment]
Thanks for reporting that one! :dancer:
