### ISSUE TITLE
Podcast icons vary in fill color

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#277]
Not positive this is a bug? Figured I'd point it out just in case, sort of drives me nuts. Also probably not related to the redesign — is there a better place to report this sort of thing or is here cool?

![screen shot 2015-10-14 at 8 32 57 am](https://cloud.githubusercontent.com/assets/8040471/10488610/5815ef1e-724e-11e5-809f-2d16f45e1d2e.png)

Some of them are #5D5D5D (paint brushes in that picture) and some are #3F403F (everything else). There wasn't any discernible pattern like alternating or anything and it's not just the brushes. Might be a couple other colors in there too, but they're not different enough to tell at a glance.

**Comment by tholman** [comment]
Fixed!
