### ISSUE TITLE
Using NodeList.js

### ISSUE THREAD

**Issue by eorroe** [CodePen/redesign#281]
Looking at the [browser support](https://blog.codepen.io/documentation/) for CodePen (bottom of page) I'm not sure if this is something you guys would be up for since [`NodeList.js`](https://github.com/eorroe/NodeList.js) has the following support:

| Browser | Version |
| --------|---------|
| FireFox | 6+      |
| Safari  | 5.0.5+  |
| Chrome  | 6+      |
| IE      | 9+      |
| Opera   | 11+     |

NodeList.js is a bit under 4k minified, and you'd be using the same file for both desktop and mobile.

So here's the one sentence I use to describe my library "Use the native DOM APIs as easily as jQuery"

We all know the native DOM APIs are fast, so my library is just a wrapper to make those same DOM APIs as easy as jQuery. Therefore if you know how to use the native DOM APIs you already know how to use NodeList.js

So NodeList.js only solves the DOM manipulation part.

What about AJAX? 
Well the only thing I can think of is the native [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) which there is a [polyfill](https://github.com/github/fetch) for. 

What about animation? If you want to use JavaScript, you'll have to find a [good small library](http://microjs.com/#jsanimation) for that. (Even though I suggest CSS for that, since it runs on a different thread)

So I would really love to see a big site like CodePen use my library, this would really help me get my library noticed more, and make CodePen faster.

Thoughts?
Thanks

**Comment by chriscoyier** [comment]
Thanks for letting us know about it, but I'm afraid changing a major dom library isn't in the cards for us.
