### ISSUE TITLE
Firefox only: Add External JavaScript form fields get error outline when filled with protocol-relative URL

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#282]
Makes it look like there's a form error. Doesn't happen to URLs that start with http or https

![screenshot 2015-10-19 14 48 30](https://cloud.githubusercontent.com/assets/456844/10587778/cc53440a-7670-11e5-8d23-79b531925263.png)

**Comment by paulirish** [comment]
<input id=inputElem type=url value="//example.com/lol.js">
    inputElem.validity.typeMismatch == true

repro: http://output.jsbin.com/vifoboduso/quiet

same on chrome. 

.... 

and turns out chris knew this from a while ago…

![image](https://cloud.githubusercontent.com/assets/39191/10599421/cfdd3086-76b6-11e5-9cdc-826160e0d212.png)

**Comment by paulirish** [comment]
i attempted to fix this but failed.

i tried to apply the `[pattern]` attribute to whitelist protocol relative URLS.

```html
 <input type=url value="//example.com/lol.js" pattern="^((ftp|http|https):)?\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$">
```

I'm using a regex from https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L752 who say they stole it from Chromium. seems good.

But no matter what i try, i can't make `type=url` apply a more liberal pattern than the default, so it'd have to move to type=text to work.

:shrugziez:

**Comment by chriscoyier** [comment]
Since we're not using HTML5 form validation on these anyway, I don't think it's a huge loss to not having them be `type="url"` 

I'm switching to `type="text"` in the next deploy with this `pattern` - thanks @paulirish
