### ISSUE TITLE
Browser back from blog post full page preview appears to erase post in Chrome

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#286]
submitted by email, I was able to reproduce it in Chrome. Refresh restores the post text. Doesn't happen in Firefox or Safari.

> If you preview full page a blog post, then hit back, the textarea shows the placeholder, not your blog text. This happens even if the blog post has been saved. Refreshing fixes the issue. [...] Browser used is Chrome 46.0.2490.71.

**Comment by chriscoyier** [comment]
Sometimes I was able to replicate it, sometimes it seemed to work perfectly.

Then I went to record it and got some even weirder behavior: http://d.pr/v/1jEVB/5lbF5BhZ

**Comment by chriscoyier** [comment]
Moved here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/15
