### ISSUE TITLE
/signup/change/pro usability

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#287]
Submitted by email (support 3766):

>The input label's do not work because they are not targeting the proper ID of the radio input. Currently, there is no way you can click the label (the "$9/month" text) and have the radio option next to it get selected.
>
>Also, it may be a good thing to swap out the default color of a selected radio input as the blue on blue background makes it hard to know which option is selected.

**Comment by tholman** [comment]
Fixed up the labels!

The whole page could use a little bit of love, really. So I left the colors for now.
