### ISSUE TITLE
Two Weird Things about Collections

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#289]
Let's not display the "actions" in the Collections grid:

<img width="747" alt="screen shot 2015-10-22 at 6 43 04 pm" src="https://cloud.githubusercontent.com/assets/69156/10681823/b8797b42-792d-11e5-8079-45d47893eb73.png">

You can do those things from the Collections page itself, and it's weird to see them without the hover. If anyone REALLY wants to keep them, let's make them appear in the correct position and on hover and with a button style that's more visible.

Also, it's weird you can't click on the title of a Collection to go to it. Must be a new z-index thing.

**Comment by tholman** [comment]
Fixed.
