### ISSUE TITLE
Hide "empty" Collections, or make Private Collections a feature

### ISSUE THREAD

**Issue by chasebank** [CodePen/redesign#290]
Half issue/half suggestion.

My private pens are a little unruly... but could be cleaned up using collections. But I don't want to muck up my public collections with a bunch of ugly housekeeping. It's also possible that users don't want to/can't publicly mention certain projects - so are forced to come up with alias titles.

Currently, when you create a collection, there's no privacy option. However, the collections page shows a 'public' tab. This is probably just a UI artifact and should be removed, unless private collections are being considered?

Personally, "real" private collections sound complicated, since they may confuse the privacy settings of their contained pens. But I think a quick fix would be to hide "empty" collections. Empty meaning, no pens that are accessible by the user.

Right now, when another user views your collections, collections with only private pens are shown, but listed as empty. If you just hide it, then that solves the problem. "Private" collections will be created naturally.

**Comment by quezo** [comment]
@chasebank Just wanted to let you know that Private Collections is very high on our list. We'll get in touch with you when it's out. We're working on a solution and we really appreciate you documenting this problem.

**Comment by chriscoyier** [comment]
I like the idea of hiding a collection if the current user can't see anything inside it anyway. That's on the list now. 

Private Collections is also under active development. Hopefully our implementation will be obvious and actually less confusing.
