### ISSUE TITLE
"+ New Pen" button isn't aligned

### ISSUE THREAD

**Issue by filipelinhares** [CodePen/redesign#293]
Ubuntu 14.04 - Google Chrome Version 48.0.2541.0

![screenshot from 2015-10-25 18 46 33](https://cloud.githubusercontent.com/assets/2338778/10717760/ed05099a-7b48-11e5-85ec-0a57834a8d33.png)

**Comment by chriscoyier** [comment]
Couldn't replicate exactly your setup, but Chrome+Ubuntu seems OK. 

![screen shot 2015-11-02 at 4 44 43 pm](https://cloud.githubusercontent.com/assets/69156/10896741/8201df76-8181-11e5-9e85-4a90b4734658.png)

Small enough of a thing I might just have to let it be for now and perhaps someday refactor that pattern such that it's impossible to have that defect.
