### ISSUE TITLE
Pixel size indicator getting cut off on browser resize

### ISSUE THREAD

**Issue by mariemosley** [CodePen/redesign#294]
Reported by email [support 3823] on Chrome 46 in Windows, and I was able to reproduce in all browsers on OSX El Capitan. Affects "Editor on Side" views only, "Editor on Top" view not affected.

Animated gif from email: http://i.imgur.com/uxO5ypu.gifv

My still screenshot, from Firefox : 
![screenshot 2015-10-27 11 59 28](https://cloud.githubusercontent.com/assets/456844/10763980/73a08542-7ca2-11e5-93cc-3fb205b5fbad.png)

**Comment by chriscoyier** [comment]
I had fixed this but forgot to push it. We'll deploy the fix in a sec.
