### ISSUE TITLE
code collapsing fail

### ISSUE THREAD

**Issue by keldonrush** [CodePen/redesign#296]
Repro Steps : 
1. visit http://codepen.io/keldon/pen/EVxvaK?editors=101
1.5 ( you can click 'tidy' to format code if you like )
2. Attempt to collapse line 21 ( "slides": [{ ) by clicking the arrow icon

Actual : 
 Only the first object of the Array collapses

Expected : 
 The entire Array would collapse.

**Comment by tholman** [comment]
Hey mate!

The behavior you're getting seems to be the default across the board (looking at sublime text and atom) ... and we want to stay as close to these as possible, to not give any unexpected surprises to new users.

That said, CodePen is using codemirror (https://codemirror.net) to give this behavior, so you might be able to take it up with them! :)

**Comment by keldonrush** [comment]
Hello Tim,

No, this is a bug.  Sublime Text and IntelliJ (and most editors) allow you
to collapse on square brackets and curly brackets.

I will take it up with codemirror.

Cheers,
Keldon

**Comment by keldonrush** [comment]
Turns out you were right - that *is* how Sublime handles arrays.

IntelliJ does the 'right' thing and folds on the array and on the object.

Cheers,
Keldon
