### ISSUE TITLE
showcase iframes not running if auto update preview option not selected

### ISSUE THREAD

**Issue by markhillard** [CodePen/redesign#297]
There are 2 pens in my showcase that show up without animated elements on initial page load. This is in reference to the **AUTO UPDATE PREVIEW** checkbox under **Settings > Behavior > Want a Run Button?**, which is not selected for both of these pens.

It appears that they aren't running when my showcase is displayed, i.e. visiting http://codepen.io/markhillard/.

Of course, if you navigate to the **Velocity.js Animation Sequence** or **Animated Instagram Photo Feed** pens, you'll be able to see the animations when they load up.

**Comment by chriscoyier** [comment]
I think this is fixed Mark. When I visit your profile I'm seeing the animations run.

**Comment by markhillard** [comment]
Nice, thanks! Yeah it's looking good now.
