### ISSUE TITLE
Live Update View & Base href conflict

### ISSUE THREAD

**Issue by Murilirum** [CodePen/redesign#298]
- Set the `base href="{whatever}"` in the DOM head
- Open Live Update view on new window, tab or device
- Edit the Pen & Save

I did this with the base href being `http://github.com` and received the following error in the Chrome Dev Tools console.

![](https://i.imgur.com/6qaYkzm.png)

**Comment by chriscoyier** [comment]
Thanks for reporting! I'm sure it's some internal URL we need that we're using a relative path for. We'll need to start using a fully qualified URL there just in case someone is using a `<base>` tag. We've fixed up a bunch of these kind of things before for the same reason, so just a matter or fixing it for this asset as well.

**Comment by Murilirum** [comment]
Ever since you wrote that article about the creative use of the `<base>` tag implementation, I've started to work with it more and more but ran into this issue when trying to see a live update on my phone.

Always happy to help out CodePen :heart:

**Comment by chriscoyier** [comment]
Moved here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/13
