### ISSUE TITLE
Pagination bug on pens?

### ISSUE THREAD

**Issue by natewiley** [CodePen/redesign#299]
I noticed this a bit ago, it shows that they don't have any pens yet if you go to a page that's too high. 
http://codepen.io/natewiley/pens/public/5920/
![No pens](http://i.imgur.com/3gFaNai.png) 
Hope it helps

**Comment by chriscoyier** [comment]
moving to new repo: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/9
