### ISSUE TITLE
Pagination buttons have weird alignment and position in activity feed

### ISSUE THREAD

**Issue by Imagine-Programming** [CodePen/redesign#3]
- http://redesign.codepen.io/[username]/activity/

In the activity feed the pagination buttons seem to be a little bit misplaced. 

![Bottom pagination](http://i.imgur.com/cpr1XAd.png)
![Top pagination](http://i.imgur.com/9dvW4I5.png)

**Comment by chriscoyier** [comment]
good catch, thanks!
