### ISSUE TITLE
jQuery randomly failing to load

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#301]
jQuery failed to load on the CodePen home page when I went to load it. Refresh fixed it, but with continued refreshes it seems to fail every 3rd-5th time or so.

![screen shot 2015-11-10 at 11 36 30 am](https://cloud.githubusercontent.com/assets/8040471/11073467/a2c67b12-879f-11e5-873c-3c67b74d3d54.png)

**Comment by alexzaworski** [comment]
Looks like assets have a chance to fail to load on any page, including Pens. Here's a screenshot of some css failing too:

![screen shot 2015-11-10 at 11 40 49 am](https://cloud.githubusercontent.com/assets/8040471/11073559/f37d06de-879f-11e5-90f9-3a99e19d3317.png)

**Comment by chriscoyier** [comment]
We're on the case! Was a bad deploy that didn't go out to all servers. Fixing now.
