### ISSUE TITLE
Jade Comment-Out Shortcut

### ISSUE THREAD

**Issue by Murilirum** [CodePen/redesign#302]
When using Jade as a preprocessor and using the shortcut keys <kbd>ctrl</kbd> + <kbd>/</kbd> it will insert the standard HTML `<!-- -->` rather than prefix the selected line(s) with `//`.

**Comment by chriscoyier** [comment]
Moving here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/10
