### ISSUE TITLE
Embed button in Editor view footer causes repeated pushes to browser history

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#303]
If you hit the embed button a bunch it pushes to the browser history each time — I'm assuming it's not meant to do so at all since it's a modal (comments don't have this problem).

Interestingly, the shortcuts modal pushes to the browser history once but does not continue to do so on repeated presses.

**Comment by chriscoyier** [comment]
Ah yes, classic case of not doing `event.preventDefault()` - I have the fix written and we'll get it out probably today. Thanks so much!
