### ISSUE TITLE
Pens playing audio from Pen Blocks

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/redesign#304]
Has this always been the case? Scared the crap out of me. Pen in question, if that helps:

http://codepen.io/pat_hg/pen/VvqMGj

**Comment by alexzaworski** [comment]
Without knowing anything about the HTML5 audio api, is it because of this?

```   
   if (typeof (webkitAudioContext) != "undefined") {
        webkitAudioContext = function() {
          return false;
        };
      }
```
Which is causing the console to log `'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.`

**Comment by chriscoyier** [comment]
I'm trying to figure out if this is fixed or not. We did recently make some tweaks to out audio-stopping stuff.

I have a fork of your Pen and it's not leaking audio for me, so maybe it's all good? If not, shoot me a URL to a page it leaks sound on and we'll check it out.

<img width="655" alt="screen shot 2015-11-23 at 10 12 55 am" src="https://cloud.githubusercontent.com/assets/69156/11340197/e6277638-91ca-11e5-836f-c15d8bfe52f0.png">
