### ISSUE TITLE
Verify "My Content" area has all the correct stuff in it

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#40]
On dev, Katie (user: kovalcin) doesn't have anything in that area, even though she does have both Pens and Collections. 

Same problem on Staging. Weird.

**Comment by tsabat** [comment]
I don't see that problem when logged in as her.

![screen shot 2015-09-30 at 14 37 45](https://cloud.githubusercontent.com/assets/636041/10207402/e0a7f29c-6780-11e5-938a-9e6e6d6bd6c9.png)

**Comment by chriscoyier** [comment]
I think the thing is that she has collections and they don't show. But we'll hear about this A LOT I think after launch if it's a real problem.
