### ISSUE TITLE
"My Pens" link

### ISSUE THREAD

**Issue by katiekovalcin** [CodePen/redesign#44]
We've been getting feedback about difficulty of finding "my pens" when you're not on the homepage, can we add a "my pens" tab easily in this list before launch?
![screen shot 2015-09-30 at 3 20 44 pm](https://cloud.githubusercontent.com/assets/2318663/10203982/2faeb654-6787-11e5-85e8-7496baff0790.png)

And if at all possible (not sure technical constraints between Mine/My team's pens) add a link to "my pens" in this dropdown somewhere?
![screen shot 2015-09-30 at 3 22 30 pm](https://cloud.githubusercontent.com/assets/2318663/10203996/43ffeea2-6787-11e5-8358-c6100c4935ad.png)

**Comment by chriscoyier** [comment]
@quezo is this easy to pull off? I think it is a pretty good addition.
