### ISSUE TITLE
Search in Organize Doesn't Work

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#49]
JavaScript error about PenPaging

<img width="570" alt="screen shot 2015-09-30 at 4 08 14 pm" src="https://cloud.githubusercontent.com/assets/69156/10206692/c706809e-678d-11e5-8763-3ef145afe0bd.png">

**Comment by chriscoyier** [comment]
Temporarily let's remove the search form until we can fix for real.

**Comment by tholman** [comment]
Removed for now. Issue moved to the main codepen repo.
