### ISSUE TITLE
The "Featured Pen" in Showcase Doesn't Show Screenshot Correctly

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#60]
<img width="487" alt="screen shot 2015-09-30 at 5 50 44 pm" src="https://cloud.githubusercontent.com/assets/69156/10210342/3d13bf78-67ab-11e5-9e6b-972155604526.png">

**Comment by quezo** [comment]
@chriscoyier I think this may be a bad reference to an image. The logic seems sound. I'll revisit after launch.

**Comment by tholman** [comment]
There was something giving these bigger heights as well. All looks resolved now.
