### ISSUE TITLE
Collab View has Disabled Settings Button (as owner)

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/redesign#72]
<img width="616" alt="screen shot 2015-10-01 at 8 07 15 am" src="https://cloud.githubusercontent.com/assets/69156/10221399/c8e035aa-6813-11e5-8e80-65e956cbbe3d.png">

**Comment by quezo** [comment]
This actually works. It just takes 30 seconds for it to be enabled when the collab session starts.
