### ISSUE TITLE
Sideways Scroll

### ISSUE THREAD

**Issue by donebydavid** [CodePen/redesign#74]
It appears

The issue seems to be caused by the width on .pen-templates-dropdown
![image](https://cloud.githubusercontent.com/assets/14917878/10221758/9e52d93e-6893-11e5-875e-a92de5fcf55f.png)

**Comment by donebydavid** [comment]
Once the dropdown on New Pen is clicked, the div seems to move into its correct location

**Comment by chriscoyier** [comment]
Good catch, fix going up in next push.
