### ISSUE TITLE
Recent activity pagination after first page is broken

### ISSUE THREAD

**Issue by laurendorman** [CodePen/redesign#75]
<img width="845" alt="screen shot 2015-10-01 at 9 26 22 am" src="https://cloud.githubusercontent.com/assets/6477234/10221810/879e650c-681e-11e5-8028-b90a1be1e673.png">

In `/activity/?page=2` onward.

**Comment by quezo** [comment]
@chriscoyier This is only a visual error.

**Comment by chriscoyier** [comment]
Fixing!
