### ISSUE TITLE
Pagination of Search Results Doesn't Maintain Query Parameters

### ISSUE THREAD

**Issue by Eitz** [CodePen/redesign#78]
The parameters in the next page link are broken.

**Comment by Eitz** [comment]
Go to the search page: http://codepen.io/search/pens?q=query
Then click next page.

**Comment by chriscoyier** [comment]
Yep I see what you mean! 

Page 1: http://codepen.io/search/pens?q=query

(click next)

Page 2: http://codepen.io/search/pens/?depth=&limit=&order=&page=2&q=query&show_forks=

Which is a totally different query with fewer results (because it removes forks I think).

**Comment by SamSolomon0611** [comment]
You need to manually enter page query on end .. 

http://codepen.io/search/pens?q=query&page=2

**Comment by tsabat** [comment]
Thanks for all the feedback!  This one is fixed.
