### ISSUE TITLE
Validate Profile URL's in Settings

### ISSUE THREAD

**Issue by donebydavid** [CodePen/redesign#79]
http or https is required for short names to be used on the profile page

First link is created without http or https, second is created with
![image](https://cloud.githubusercontent.com/assets/14917878/10222152/cc2fe980-6895-11e5-8fe2-8063bfccee39.png)

**Comment by fallenartist** [comment]
Also, if you have more links, they are being overlapped by avatar on the profile page.

**Comment by chriscoyier** [comment]
We need to validate these URL's in the standard HTML5 way:

<img width="619" alt="screen shot 2015-10-01 at 10 24 19 am" src="https://cloud.githubusercontent.com/assets/69156/10225071/a06069ac-6826-11e5-8348-fb8c3348b35f.png">

**Comment by chriscoyier** [comment]
@fallenartist Hopefully it will be a bit better when the validation is fixed, because we truncate the links to be just the root URL and TLD (e.g. "github.com") and thus they are generally pretty short URLs. We can't guarantee that, so some overlap is still possible tho.

**Comment by tsabat** [comment]
URL validation added, will go up with next push.
