### ISSUE TITLE
settings/profile -> bio -> About You - remaining characters

### ISSUE THREAD

**Issue by Imagine-Programming** [CodePen/redesign#80]
In the settings/profile page, the Bio section, the About You block doesn't show you how many remaining characters you have left. It would be useful if it did, considering you've hit a 100 before you know it.

**Comment by chriscoyier** [comment]
@tsabat said he can fix from the Rails side

I can fix from a `maxlength` or whatever property on the textarea

@quezo we should do a character countdown thing in the UI here too

**Comment by tsabat** [comment]
fixed validation for bio size.  Still need countdown?

**Comment by Imagine-Programming** [comment]
@tsabat it would help letting the user know before they hit a 100. 100 characters is quite easy to reach.

**Comment by chriscoyier** [comment]
Adding in the next thingy. Both special UI for it and a `maxlength`
