### ISSUE TITLE
Incorrect icon on Keyboard Commands button

### ISSUE THREAD

**Issue by ricardozea** [CodePen/redesign#81]
Let me start by saying that the new design effin' rox! :+1: 

In Chrome 45.0.2454.101 m, Win 10, the Keyboard Commands button is showing an incorrect icon:

![screenshot - 10_1_2015 9_42_44 am](https://cloud.githubusercontent.com/assets/1656481/10222298/37bc5b18-6821-11e5-8405-1649445d92fd.png)

**Comment by chriscoyier** [comment]
I wasn't able to replicate on Win 10 Chrome weirdly. But nevertheless, that symbol is meaningless on Windows even if it does work, so I went with: 

![screen shot 2015-10-06 at 11 34 50 am](https://cloud.githubusercontent.com/assets/69156/10315184/5c67d11c-6c1e-11e5-9a8a-84d1ffd7e619.png)

**Comment by ricardozea** [comment]
+1 for the text version.
