### ISSUE TITLE
".article p" has max-width: 500px, but article has no max-width

### ISSUE THREAD

**Issue by Fotiman** [CodePen/redesign#82]
The result is that there's a lot of whitespace to the right of the text, while headings and images still fill all of the available width.  Note, I noticed this while reading the blog (see screenshot).  I can't tell if this is by design or an oversight.

![short-paragraph-capture](https://cloud.githubusercontent.com/assets/351953/10222260/016641d2-6821-11e5-959b-bf1f8c482d06.PNG)

**Comment by chriscoyier** [comment]
that one is kinda intentional. It's limiting the line length (for readability) of text that really needs it. It does look a bit weird, and we'll likely address that when we can properly redesign the blog. (it was a third-class citizen for this first phase, for sure.)
