### ISSUE TITLE
Modal Button Contrast

### ISSUE THREAD

**Issue by timseverien** [CodePen/redesign#85]
The contrast between the modal button and it’s background is little; it took me a while to understand it was there at all.

I suggest to use colour, perhaps a border to make the button more prominent and easier to recognise.

![screen shot 2015-10-01 at 15 42 45](https://cloud.githubusercontent.com/assets/2920299/10222402/04669ade-6854-11e5-9b01-10e58bb0cac5.png)

**Comment by chriscoyier** [comment]
I can see that. We've opted for the outline button style when contrast is hurting that situation, I'll go for that style here.
