### ISSUE TITLE
Pen settings modal not centerally aligned

### ISSUE THREAD

**Issue by craigcoles** [CodePen/redesign#86]
Not sure if this was intentional, either way. Screenshot attached.

![cqpddxnu8ae_jzv](https://cloud.githubusercontent.com/assets/996430/10222543/8f4491cc-684c-11e5-9303-da87a68800ec.png)

**Comment by chriscoyier** [comment]
Fixing!

**Comment by craigcoles** [comment]
Nice work!

![giphy](https://cloud.githubusercontent.com/assets/996430/10226179/eca55c32-685d-11e5-984c-3a46f82d1bc8.gif)
