### ISSUE TITLE
Horizontal scroll on many pages

### ISSUE THREAD

**Issue by futekov** [CodePen/redesign#87]
Middle-clicking on the page allows for horizontal scroll.

Here are some of the pages affected:
http://codepen.io/
http://codepen.io/jobs/
http://codepen.io/patterns/

The common between them is that they have the rich top menu and that they have this element that is causing the overflow:
```
<div class="pen-templates-dropdown is-dropdown link-list" id="pen-templates-dropdown"></div>
```

Clicking the `New Pen` dropdown fixes the overflow issue, probably the div should be properly hidden before it's used.

**Comment by chriscoyier** [comment]
Fix should be out or going out very soon, thank you!
