### ISSUE TITLE
font-smoothing

### ISSUE THREAD

**Issue by baptistebriel** [CodePen/redesign#89]
I feel like the site would be way better with `font-smoothing` — what do you think about that?
Any particular reasons why this wasn't added to the site?

**Comment by chriscoyier** [comment]
I don't know that much about it. I googled it and then tested `-webkit-font-smoothing: antialiased;` on the whole document, but it just thinned out the fonts and I thought it looked a bit worse. I'd be hesitant to add something like that without 1) clearly thinking it's an improvement 2) understanding the performance and cross-browser implications.
