### ISSUE TITLE
Pen titles appearing in different pens  

### ISSUE THREAD

**Issue by mattliebetrau** [CodePen/redesign#90]
Ex. notice the "SVG Lava Lamp" title is on the 3rd pen instead of the 4th like it's supposed to be.

![screen shot 2015-10-01 at 9 59 19 am](https://cloud.githubusercontent.com/assets/5607285/10222666/3d9b3c8c-6823-11e5-97f9-6dc056d6b9f6.png)

**Comment by randseay** [comment]
Just encountered this as well, specifically after using the browser's *back* button. All of the pen images have shifted (The first pen is titled Moonwalk, but the Moonwalk image is on the second pen, and so on).
<img width="1552" alt="screen shot 2015-10-01 at 9 24 49 am" src="https://cloud.githubusercontent.com/assets/4110122/10223491/c5db9646-681e-11e5-9024-4eeb9e7fd308.png">

**Comment by hagata** [comment]
Noticing the same thing in other areas where Pens are listed; like the profile pages. 

![screen shot 2015-10-01 at 8 19 05 am](https://cloud.githubusercontent.com/assets/2608893/10224934/39dec14e-6815-11e5-88cc-ced1f10168b9.png)

"glow worm" image should is actually "simple button hover", "simple button hover" image is actually "Neat Parallax Hero Effect" ect.

**Comment by alexzaworski** [comment]
Is this possibly related to the bug that was causing ads to move around in Chrome on the old CodePen? [Here's](https://code.google.com/p/chromium/issues/detail?can=2&q=iframe&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=395533&thanks=395533&ts=1405933036) a link to that, if helpful.

**Comment by chriscoyier** [comment]
It MIGHT be that. But this bug is WEIRD and will take a minute to dig into.

**Comment by chriscoyier** [comment]
I wonder if we do that thing were we give all iframes a unique `name` attribute, it would help this @quezo

**Comment by quezo** [comment]
We've just started adding a name and title to every iFrame. We're hoping this fixes the back button bug here. Please let us know if it still errors out.
