### ISSUE TITLE
User menu :focus

### ISSUE THREAD

**Issue by timseverien** [CodePen/redesign#91]
The items’ text of the user menu turn white when the `:focus` pseudo-selector is applied, causing it to appear invisible. In general use, it won’t be much of a problem because the `:hover` pseudo-selector overwrites that style, when using keyboard navigation however, `:focus` is triggered exclusively. I guess that component is merely missing a `:focus` style.

![screen shot 2015-10-01 at 15 58 51](https://cloud.githubusercontent.com/assets/2920299/10222633/57105dbe-6855-11e5-9736-78c7bab745ad.png)

**Comment by chriscoyier** [comment]
Oops! Weird. Usually we're pretty good about that but that focus style was missing. Can't tell ya how many times I write:

```scss
  &:hover,
  &:focus {

  }
```

**Comment by timseverien** [comment]
Looks excellent now 👏
