### ISSUE TITLE
Settings "Save and close" button can be pushed off screen

### ISSUE THREAD

**Issue by Fotiman** [CodePen/redesign#92]
For window sizes about 800px tall, the Save and close button is pushed off screen with no way to get to it.  Additionally, this can be made worse by adding a lot of JavaScript or CSS resources.

![image](https://cloud.githubusercontent.com/assets/351953/10222803/f0043ec8-6823-11e5-90cf-c56d5bc08956.png)

![image](https://cloud.githubusercontent.com/assets/351953/10222758/b13f4a02-6823-11e5-841a-b181837ef381.png)

**Comment by myerscourtney** [comment]
It looks like the ".pen-settings-halfs-wrap" div has a max-height of "80vw". Switching from viewport width to viewport height units could do the trick (and maybe even reducing it a bit to "75vh" in case your browser window's height isn't very tall).

**Comment by chriscoyier** [comment]
Oops, used the wrong unit there. Fixing this in the next push. Thank you!

**Comment by myerscourtney** [comment]
Thanks @chriscoyier :) Love the redesign!
