### ISSUE TITLE
404 form needs some love

### ISSUE THREAD

**Issue by donebydavid** [CodePen/redesign#93]

**Comment by chriscoyier** [comment]
This is what I see:

![Uploading Screen Shot 2015-10-01 at 9.23.39 AM.png…]()

Which is our intended design. Does it look different or does it look broken as is to you? (Re-open if so).

**Comment by donebydavid** [comment]
![image](https://cloud.githubusercontent.com/assets/14917878/10223399/218cb6a0-689c-11e5-8ca3-4d42d48f2f5e.png)

compared to the support form
![image](https://cloud.githubusercontent.com/assets/14917878/10223416/39968dfc-689c-11e5-9f44-e7d793f6c0a6.png)
