### ISSUE TITLE
Unable to add avatar

### ISSUE THREAD

**Issue by donebydavid** [CodePen/redesign#96]
Select files does nothing once file is selected

Unable to copy file into browser to upload

**Comment by nicovanzyl** [comment]
Drag & Drop doesn't work either.

**Comment by hugoender** [comment]
I am having same issue on Mac with Chrome and Firefox. I cannot change my profile picture.

**Comment by RavingAPD** [comment]
Same thing here.
Love the new redesign though!

**Comment by chriscoyier** [comment]
Found the problem! Fix going out now.
